# Generated by Django 3.0.8 on 2021-08-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correio_eletronico', '0002_correioeletronico_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correioeletronico',
            old_name='origem',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='correioeletronico',
            old_name='correio_eletronico',
            new_name='mensagem',
        ),
        migrations.RemoveField(
            model_name='correioeletronico',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='correioeletronico',
            name='user',
        ),
        migrations.AlterField(
            model_name='correioeletronico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
